local mod = SomethingWicked
mod.ITEMS = {}

mod.ITEMS.AVENGER_EMBLEM = Isaac.GetItemIdByName("Avenger Emblem")
mod.ITEMS.BOLINE = Isaac.GetItemIdByName("Boline")
mod.ITEMS.BOOK_OF_EXODUS = Isaac.GetItemIdByName("Book of Exodus")
mod.ITEMS.D_STOCK = Isaac.GetItemIdByName("D-Stock")
mod.ITEMS.WICKED_SOUL = Isaac.GetItemIdByName("Wicked Soul")
mod.ITEMS.WOODEN_HORN = Isaac.GetItemIdByName("Wooden Horn")
mod.ITEMS.SILVER_RING = Isaac.GetItemIdByName("Silver Ring")
mod.ITEMS.WHITE_ROSE = Isaac.GetItemIdByName("White Rose")
mod.ITEMS.STAR_SPAWN = Isaac.GetItemIdByName("Star Spawn")
mod.ITEMS.ITEM_BOX = Isaac.GetItemIdByName("Item Box")
mod.ITEMS.WOODEN_DICE = Isaac.GetItemIdByName("Wooden Dice")

mod.ITEMS.BOTTLE_OF_SHAMPOO = Isaac.GetItemIdByName("Bottle of Shampoo") -- just give a costume? Test

mod.ITEMS.THREED_GLASSES = Isaac.GetItemIdByName(" 3D Glasses ")
mod.ITEMS.ABANDONED_BOX = Isaac.GetItemIdByName("Abandoned Box")
mod.ITEMS.AIR_FRESHENER = Isaac.GetItemIdByName("Air Freshener") --unfinished
mod.ITEMS.APOLLYONS_CROWN = Isaac.GetItemIdByName("Apollyon's Crown") --retouch
mod.ITEMS.ASSIST_TROPHY = Isaac.GetItemIdByName("Assist Trophy")
mod.ITEMS.BABY_MANDRAKE = Isaac.GetItemIdByName("Baby Mandrake") --unfinished
mod.ITEMS.BALROGS_HEAD = Isaac.GetItemIdByName("Balrog's Head")
mod.ITEMS.BALROGS_HEART = Isaac.GetItemIdByName("Balrog's Heart") --unfinished (might deserve not balrog-ness)
mod.ITEMS.FRUIT_MILK = Isaac.GetItemIdByName("Fruit Milk") --unfinished
mod.ITEMS.ELECTRIC_DICE = Isaac.GetItemIdByName("Electric Dice")
mod.ITEMS.BIRETTA = Isaac.GetItemIdByName("Biretta") -- touch up
mod.ITEMS.BLACK_SALT = Isaac.GetItemIdByName("Black Salt") --unfinsihed
mod.ITEMS.BLOOD_HAIL = Isaac.GetItemIdByName("Blood Hail") --unfinished
mod.ITEMS.BOOK_OF_INSANITY = Isaac.GetItemIdByName("King in Yellow") -- nightmares in general need retouch
mod.ITEMS.BOOK_OF_LEVIATHAN = Isaac.GetItemIdByName("  Book of Leviathan  ") --unfinished
mod.ITEMS.BOOK_OF_LUCIFER = Isaac.GetItemIdByName("Book of Lucifer") -- needs retouch
mod.ITEMS.BRAVERY = Isaac.GetItemIdByName("Bravery")
mod.ITEMS.NAGA_VIPER = Isaac.GetItemIdByName("Naga Viper")
mod.ITEMS.CAROLINA_REAPER = Isaac.GetItemIdByName("Carolina Reaper")
mod.ITEMS.CAT_FOOD = Isaac.GetItemIdByName("Cat Food") -- retouch
mod.ITEMS.CAT_TEASER = Isaac.GetItemIdByName("Cat Teaser")
mod.ITEMS.FUZZY_FLY = Isaac.GetItemIdByName("Fuzzy Fly") --unfinished
mod.ITEMS.CHAOS_HEART = Isaac.GetItemIdByName("Chaos Heart") -- entire redesign now
mod.ITEMS.CHASM = Isaac.GetItemIdByName("Chasm") --retouch
mod.ITEMS.CHRISMATORY = Isaac.GetItemIdByName("Chrismatory") --fix weird bug with angellic lyre. maybe move effect to different item then make this like spectre
mod.ITEMS.CROSSED_HEART = Isaac.GetItemIdByName("Crossed Heart")
mod.ITEMS.CURSED_CANDLE = Isaac.GetItemIdByName("Cursed Candle")
mod.ITEMS.CURSED_CREDIT_CARD = Isaac.GetItemIdByName("Cursed Credit Card")
mod.ITEMS.CURSED_MUSHROOM = Isaac.GetItemIdByName("Cursed Mushroom")
mod.ITEMS.CURSE_MASK = Isaac.GetItemIdByName("Curse Mask") --unfinished
mod.ITEMS.BLACK_MOON_MEDALLION = Isaac.GetItemIdByName("Black Moon Medallion") --unfinished
mod.ITEMS.CUTIE_FLY_ITEM = Isaac.GetItemIdByName("Cutie Fly") --unfinished
mod.ITEMS.DADS_WALLET = Isaac.GetItemIdByName("Lost Wallet")
mod.ITEMS.EVIL_PIGGYBANK = Isaac.GetItemIdByName("Mammon's Piggybank") --unfinished
mod.ITEMS.DARKNESS = Isaac.GetItemIdByName("Darkness") --unfinished
mod.ITEMS.DEVILSKNIFE_ITEM = Isaac.GetItemIdByName("Devilsknife")
mod.ITEMS.DEVILSTAIL = Isaac.GetItemIdByName("Devil's Tail") --REDO
mod.ITEMS.DISCIPLES_EYE = Isaac.GetItemIdByName("Disciple's Eye") --re-do or scrap. atleast resprite
mod.ITEMS.DUDAEL = Isaac.GetItemIdByName("Dudael") -- unfinished
mod.ITEMS.EDENS_HEAD = Isaac.GetItemIdByName("Eden's Head")
mod.ITEMS.ENCYCLOPEDIA = Isaac.GetItemIdByName("Encyclopedia")
mod.ITEMS.EYE_OF_PROVIDENCE = Isaac.GetItemIdByName("Eye of Providence") -- unfinished, might also deserve a redo
mod.ITEMS.FLYING_GUILLOTINE = Isaac.GetItemIdByName("Facestabber") -- technically finished, but i want to retouch before pushing
mod.ITEMS.LIGHTHOUSE = Isaac.GetItemIdByName("Lighthouse") --unfinished
mod.ITEMS.FEAR_STALKS_THE_LAND = Isaac.GetItemIdByName("Fear Stalks The Land!") --mega unfinished. dread deserves an entire retouch before i add it in
mod.ITEMS.FETUS_IN_FETU = Isaac.GetItemIdByName("Fetus in Fetu") -- in process of retouch
mod.ITEMS.FITUS_FORTUNUS = Isaac.GetItemIdByName("Fitus Fortunus") -- in need of retouch
mod.ITEMS.TRINKET_SMASHER = Isaac.GetItemIdByName("Trinket Smasher")
mod.ITEMS.GANYMEDE = Isaac.GetItemIdByName(" Ganymede ") --unfinished, make this cool
mod.ITEMS.GLITCHCITY = Isaac.GetItemIdByName("GLITCHCITY") -- possibly retouch
mod.ITEMS.GOLDEN_CARD = Isaac.GetItemIdByName("Golden Card") -- maybe retouch or resprite
mod.ITEMS.BOOSTER_BOX = Isaac.GetItemIdByName("Booster Box") -- give this a costume 
mod.ITEMS.GOLDEN_WATCH = Isaac.GetItemIdByName("Golden Watch") -- unfinished, literally just needs pooling and on purchase break
mod.ITEMS.HELLFIRE = Isaac.GetItemIdByName("Hellfire")
mod.ITEMS.CROWN_OF_BLOOD = Isaac.GetItemIdByName("Martyral Baptism") -- unfinished, might deserve thematic redesign.
mod.ITEMS.ICE_WAND = Isaac.GetItemIdByName("Ice Wand") -- unfinished
mod.ITEMS.JOKER_BABY = Isaac.GetItemIdByName("Joker Baby") -- unfinished, god please finish this
mod.ITEMS.JUSTICE_AND_SPLENDOR = Isaac.GetItemIdByName("Swords of Light") -- fix weird visual bug and maybe add some sfx
mod.ITEMS.LANKY_MUSHROOM = Isaac.GetItemIdByName("Lanky Mushroom")
mod.ITEMS.LANTERN_BATTERY = Isaac.GetItemIdByName("Lantern Battery") -- minor retouch
mod.ITEMS.LAST_PRISM = Isaac.GetItemIdByName("Last Prism") -- unfinished, FINISH PLEAAAAAAAAASE
mod.ITEMS.LEGION_ITEM = Isaac.GetItemIdByName("Legion") --unfinished, please finish me
mod.ITEMS.DOUBLING_CHERRY = Isaac.GetItemIdByName("Doubling Cherry") -- unfinished, just needs item sprites and some minor anm2 stuff
mod.ITEMS.LIGHT_SHARD = Isaac.GetItemIdByName("Light Shard") -- unfinished, retouch maybe
mod.ITEMS.DARK_SHARD = Isaac.GetItemIdByName("Dark Shard") --same as above
mod.ITEMS.LITTLE_ATTRACTOR_ITEM = Isaac.GetItemIdByName("Little Attractor") -- unfinished
mod.ITEMS.LOURDES_WATER = Isaac.GetItemIdByName("Lourdes Water") -- fix two bugs
mod.ITEMS.LOVERS_MASK = Isaac.GetItemIdByName("Lover's Mask") -- retouch
mod.ITEMS.MAGIC_CLAY = Isaac.GetItemIdByName("Magic Clay") -- unfinished, i really like this one though finish it
mod.ITEMS.MINOS_ITEM = Isaac.GetItemIdByName("Minos") -- retouch me to hell
mod.ITEMS.CRYING_MINOTAUR = Isaac.GetItemIdByName("Crying Minotaur") -- unfinished, see FSTL (might deserve not-radiohead ness)
mod.ITEMS.THE_MISTAKE = Isaac.GetItemIdByName("The Mistake") -- most unfinished item in the mod
mod.ITEMS.MS_GONORRHEA = Isaac.GetItemIdByName("Ms. Gonorrhea") -- unfinished, just needs design
mod.ITEMS.STAR_OF_THE_BOTTOMLESS_PIT = Isaac.GetItemIdByName("Star of the Bottomless Pit")
mod.ITEMS.NIGHTSHADE = Isaac.GetItemIdByName("Nightshade") -- weird, retouch
mod.ITEMS.OLD_DICE = Isaac.GetItemIdByName("Old Dice") -- check bug tet mentioned
mod.ITEMS.OLD_URN = Isaac.GetItemIdByName("Old Urn") -- retouch
mod.ITEMS.PENDULUM = Isaac.GetItemIdByName("Pendulum") -- so close to finished
mod.ITEMS.PIECE_OF_SILVER = Isaac.GetItemIdByName("Piece of Silver") -- so close to finished
mod.ITEMS.PLANCHETTE = Isaac.GetItemIdByName("Planchette") -- maybe retouch
mod.ITEMS.PLASMA_GLOBE = Isaac.GetItemIdByName("Plasma Globe")
mod.ITEMS.PRESSURE_VALVE = Isaac.GetItemIdByName("Pressure Valve") -- unfinished. release with costume or die
mod.ITEMS.PRISMATIC_MUSHROOM = Isaac.GetItemIdByName("Prismatic Mushroom") -- unfinished
mod.ITEMS.RAMS_HEAD = Isaac.GetItemIdByName("Ram's Head") -- add costume for the love of god
mod.ITEMS.RED_NIGHTMARE = Isaac.GetItemIdByName("Red") -- resprite and retouch
mod.ITEMS.RED_CAP = Isaac.GetItemIdByName("Red Cap") -- retouch, probably. maybe just costume
mod.ITEMS.RED_LOCKBOX = Isaac.GetItemIdByName("Red Lockbox") -- slight retouch deserved
mod.ITEMS.RED_QUEEN = Isaac.GetItemIdByName("Red Queen") -- gretouch and unfinished
mod.ITEMS.RELIQUARY = Isaac.GetItemIdByName("Reliquary") -- unfinished but peak
mod.ITEMS.REGEN_RING = Isaac.GetItemIdByName("Band of Regeneration") -- fuck i hate to say retouch and resprite on something this recent buuut
mod.ITEMS.ROGUE_PLANET_ITEM = Isaac.GetItemIdByName("Rogue planet") -- a million retouches
mod.ITEMS.WICKERMAN = Isaac.GetItemIdByName("Wickerman") -- give costume? also i dont like the on pickup effect
mod.ITEMS.TEMPERANCE = Isaac.GetItemIdByName("Temperance") -- unfinished, release with costume or die
mod.ITEMS.SAINTS_HEAD = Isaac.GetItemIdByName("Saint's Head") -- unfinished, love this one though
mod.ITEMS.SCREW_ATTACK = Isaac.GetItemIdByName("Screw Attack") -- finish for the love of god
mod.ITEMS.SHOTGRUB = Isaac.GetItemIdByName("The Black Death") -- possibly re-do entirely
mod.ITEMS.SOLOMON_ITEM = Isaac.GetItemIdByName("Solomon") -- retouch
mod.ITEMS.SPIDER_EGG = Isaac.GetItemIdByName("Spider Egg") -- retouch for the love
mod.ITEMS.STICKER_BOOK = Isaac.GetItemIdByName("Sticker Book") -- unfinished
mod.ITEMS.SUPERIORITY = Isaac.GetItemIdByName("Superiority") --idk man a costume would be nice
mod.ITEMS.TECH_MODULO = Isaac.GetItemIdByName("Tech-Modulo") -- give me tear colour and costume
mod.ITEMS.TERATOMA_CHUNK = Isaac.GetItemIdByName("Teratoma Chunk") -- entire redesign now
mod.ITEMS.TIAMATS_DICE = Isaac.GetItemIdByName("Tiamat's Dice") -- minor retouch needed
mod.ITEMS.TOMBSTONE = Isaac.GetItemIdByName("Tombstone") -- unfinished
mod.ITEMS.TOYBOX = Isaac.GetItemIdByName("Toybox") -- retouch possibly
mod.ITEMS.VOID_BOMBS = Isaac.GetItemIdByName("Void Bombs") -- resprite, give scatter costumes
mod.ITEMS.VOID_EGG = Isaac.GetItemIdByName("Void Egg") --idfk man, retouch?
mod.ITEMS.CALL_OF_THE_VOID = Isaac.GetItemIdByName("Void's Call") -- finish asap
mod.ITEMS.STRANGE_APPLE = Isaac.GetItemIdByName("Strange Apple") -- rework visuals and movement/tile size thing
--mod.ITEMS.WHITE_ROBE = Isaac.GetItemIdByName("White Robe") -- maybe rework entirely
mod.ITEMS.WRATH = Isaac.GetItemIdByName("Wrath") -- minor retouch, maybe
mod.ITEMS.YELLOW_SIGIL = Isaac.GetItemIdByName("Yellow Sigil") -- retouch when nightmares retouched
mod.ITEMS.THE_YOYO = Isaac.GetItemIdByName("The Yo-Yo!") -- unfinished
mod.ITEMS.HYDRUS = Isaac.GetItemIdByName("Snake")
mod.ITEMS.WICKED_RING = Isaac.GetItemIdByName("Wicked Ring")
mod.ITEMS.STAR_TREAT = Isaac.GetItemIdByName("Star Treat")
mod.ITEMS.SEED_OF_EDEN = Isaac.GetItemIdByName("Seed of Eden")
mod.ITEMS.SEED_OF_EDEN_PASSIVE = Isaac.GetItemIdByName(" Seed of Eden ")
mod.ITEMS.DIS = Isaac.GetItemIdByName("Dis")
mod.ITEMS.ACHERON = Isaac.GetItemIdByName("Acheron")

--trinkets
mod.TRINKETS = {}
mod.TRINKETS.TICKET_ROLL = Isaac.GetTrinketIdByName("Ticket Roll") -- retouch
mod.TRINKETS.BUSTED_BATTERY = Isaac.GetTrinketIdByName("Busted Battery") --unfinished
mod.TRINKETS.GODLY_TOMATO = Isaac.GetTrinketIdByName("Godly Tomato") -- retouch
mod.TRINKETS.HALLOWEEN_CANDY = Isaac.GetTrinketIdByName("Halloween Candy") --unfinsihed
mod.TRINKETS.POPPET = Isaac.GetTrinketIdByName("Poppet")
mod.TRINKETS.BOBS_HEART = Isaac.GetTrinketIdByName("Bob's Heart") -- retouch
mod.TRINKETS.SCORCHED_PAGE = Isaac.GetTrinketIdByName("Scorched Page") --unfinished
mod.TRINKETS.CATS_EYE = Isaac.GetTrinketIdByName("Cat's Eye")
mod.TRINKETS.MEAL_COUPON = Isaac.GetTrinketIdByName("Meal Coupon") -- unfinished
mod.TRINKETS.DAMNED_SOUL = Isaac.GetTrinketIdByName("Damned Soul")
mod.TRINKETS.VIRTUOUS_SOUL = Isaac.GetTrinketIdByName("Virtuous Soul") --remove or redesign
mod.TRINKETS.DEMON_CORE = Isaac.GetTrinketIdByName("Demon Core") -- retouch
mod.TRINKETS.DEMONIUM_PAGE = Isaac.GetTrinketIdByName("Demonium Page")
mod.TRINKETS.DICE_ROLLER = Isaac.GetTrinketIdByName("Dice Roller")
mod.TRINKETS.EMPTY_BOOK = Isaac.GetTrinketIdByName("Blank Book") -- might deserve a resprite
mod.TRINKETS.GACHAPON = Isaac.GetTrinketIdByName("Gachapon") -- needs retouch, maybe resprite?
mod.TRINKETS.GIFT_CARD = Isaac.GetTrinketIdByName("Gift Card") -- needs retouch
mod.TRINKETS.CARD_GRAVEYARD = Isaac.GetTrinketIdByName("Card Graveyard") -- unfinished
mod.TRINKETS.CELLPHONE_BATTERY = Isaac.GetTrinketIdByName("Cellphone Battery")
mod.TRINKETS.LUCKY_BUTTON = Isaac.GetTrinketIdByName("Lucky Button") --unfinished, just needs sprite
mod.TRINKETS.MR_SKITS = Isaac.GetTrinketIdByName("Mr. Skits") -- unfinished
mod.TRINKETS.OWL_FEATHER = Isaac.GetTrinketIdByName("Owl Feather") -- maybe resprite? animals r hard
mod.TRINKETS.NIGHTMARE_FUEL = Isaac.GetTrinketIdByName("Nightmare Fuel") -- retouch this to hell and back
mod.TRINKETS.VIRTUE = Isaac.GetTrinketIdByName("Virtue") -- unfinished as hell
mod.TRINKETS.POWER_INVERTER = Isaac.GetTrinketIdByName("Power Inverter")
mod.TRINKETS.RED_KEYCHAIN = Isaac.GetTrinketIdByName("Red Keychain") -- unfinished
mod.TRINKETS.SURGICAL_MASK = Isaac.GetTrinketIdByName("Surgical Mask") -- unfinished, justn eeds sprite
mod.TRINKETS.SCORCHED_WOOD = Isaac.GetTrinketIdByName("Scorched Wood") -- retouch
mod.TRINKETS.STONE_KEY = Isaac.GetTrinketIdByName("Stone Key")
mod.TRINKETS.SUGAR_COATED_PILL = Isaac.GetTrinketIdByName("Sugar Coated Pill") --retouch
mod.TRINKETS.TREASURERS_KEY = Isaac.GetTrinketIdByName("Treasurer's Key")
mod.TRINKETS.CURSED_KEY = Isaac.GetTrinketIdByName("Cursed Key")
mod.TRINKETS.TWO_OF_COINS = Isaac.GetTrinketIdByName("Two of Coins") -- retouch. gotta do the gold thing probably.
mod.TRINKETS.VOID_HEART = Isaac.GetTrinketIdByName("Void Heart") -- retouch rn
mod.TRINKETS.ZZZZZZ_MAGNET = Isaac.GetTrinketIdByName("ZZZZZZ Magnet") -- unfinished
mod.TRINKETS.PRINT_OF_INDULGENCE = Isaac.GetTrinketIdByName("Indulgence Print")
mod.TRINKETS.SAMPLE_BOX = Isaac.GetTrinketIdByName("Sample Box")

--CARDS
mod.CARDS = {}
mod.CARDS.MAGPIE_EYE = Isaac.GetCardIdByName("MagpieEye")
mod.CARDS.MAGPIE_EYE_BOON = Isaac.GetCardIdByName("MagpieEyeBoon")
mod.CARDS.KNIGHT_OF_DIAMONDS = Isaac.GetCardIdByName("KnightOfDiamonds")
mod.CARDS.KNIGHT_OF_HEARTS = Isaac.GetCardIdByName("KnightOfHearts")
mod.CARDS.KNIGHT_OF_SPADES = Isaac.GetCardIdByName("KnightOfSpades")
mod.CARDS.KNIGHT_OF_CLUBS = Isaac.GetCardIdByName("KnightOfClubs")
mod.CARDS.THE_GAME = Isaac.GetCardIdByName("TheGame") --that you just lost
mod.CARDS.STONE_OF_THE_PIT = Isaac.GetCardIdByName("StoneOfThePit")

mod.CARDS.THOTH_THE_ADJUSTMENT = Isaac.GetCardIdByName("TheAdjustment")
mod.CARDS.THOTH_THE_AEON = Isaac.GetCardIdByName("TheAeon")
mod.CARDS.THOTH_ART = Isaac.GetCardIdByName("TheArt")
mod.CARDS.THOTH_FORTUNE = Isaac.GetCardIdByName("Fortune")
mod.CARDS.THOTH_LUST = Isaac.GetCardIdByName("Lust")
mod.CARDS.THOTH_THE_MAGUS = Isaac.GetCardIdByName("TheMagus")


local itemPoolEnum = mod.ItemPools
mod.CONST.POOLS = {
    [itemPoolEnum.TERATOMA_BEGGAR] = {
        { item = mod.ITEMS.FETUS_IN_FETU, weight = 1},
        { item = mod.ITEMS.TERATOMA_CHUNK, weight = 1}
    }
}

mod.CONST.DUMMYITEMS = {
    LUST_NULLITEM = Isaac.GetItemIdByName("[sw] lust dummy helper"),
    BLANKBOOK_BOOKWORM = Isaac.GetItemIdByName("[sw] bookworm dummy item"),
    BLANKBOOK_GOLDEN = Isaac.GetItemIdByName("[sw] golden bookworm dummy item")
}