local mod = SomethingWicked
SomethingWicked.ITEMS = {}

SomethingWicked.ITEMS.AVENGER_EMBLEM = Isaac.GetItemIdByName("Avenger Emblem")
SomethingWicked.ITEMS.BOLINE = Isaac.GetItemIdByName("Boline")
SomethingWicked.ITEMS.BOOK_OF_EXODUS = Isaac.GetItemIdByName("Book of Exodus")
SomethingWicked.ITEMS.D_STOCK = Isaac.GetItemIdByName("D-Stock")
SomethingWicked.ITEMS.WICKED_SOUL = Isaac.GetItemIdByName("Wicked Soul")
SomethingWicked.ITEMS.WOODEN_HORN = Isaac.GetItemIdByName("Wooden Horn")
SomethingWicked.ITEMS.SILVER_RING = Isaac.GetItemIdByName("Silver Ring")
SomethingWicked.ITEMS.WHITE_ROSE = Isaac.GetItemIdByName("White Rose")
SomethingWicked.ITEMS.STAR_SPAWN = Isaac.GetItemIdByName("Star Spawn")
SomethingWicked.ITEMS.ITEM_BOX = Isaac.GetItemIdByName("Item Box")
SomethingWicked.ITEMS.WOODEN_DICE = Isaac.GetItemIdByName("Wooden Dice")
SomethingWicked.ITEMS.BOTTLE_OF_SHAMPOO = Isaac.GetItemIdByName("Bottle of Shampoo") 
SomethingWicked.ITEMS.THREED_GLASSES = Isaac.GetItemIdByName(" 3D Glasses ")
SomethingWicked.ITEMS.ABANDONED_BOX = Isaac.GetItemIdByName("Abandoned Box")
SomethingWicked.ITEMS.AIR_FRESHENER = Isaac.GetItemIdByName("Air Freshener") --unfinished
SomethingWicked.ITEMS.APOLLYONS_CROWN = Isaac.GetItemIdByName("Apollyon's Crown") --retouch
SomethingWicked.ITEMS.ASSIST_TROPHY = Isaac.GetItemIdByName("Assist Trophy")
SomethingWicked.ITEMS.BABY_MANDRAKE = Isaac.GetItemIdByName("Baby Mandrake") --unfinished
SomethingWicked.ITEMS.BALROGS_HEAD = Isaac.GetItemIdByName("Balrog's Head")
SomethingWicked.ITEMS.BALROGS_HEART = Isaac.GetItemIdByName("Balrog's Heart") --unfinished (might deserve not balrog-ness)
SomethingWicked.ITEMS.FRUIT_MILK = Isaac.GetItemIdByName("Pink Milk") --unfinished
SomethingWicked.ITEMS.ELECTRIC_DICE = Isaac.GetItemIdByName("Electric Dice")
SomethingWicked.ITEMS.BIRETTA = Isaac.GetItemIdByName("Biretta") -- touch up
SomethingWicked.ITEMS.WITCHS_SALT = Isaac.GetItemIdByName("Witch's Salt") --unfinsihed
SomethingWicked.ITEMS.BLOOD_HAIL = Isaac.GetItemIdByName("Blood Hail") --unfinished
SomethingWicked.ITEMS.BOOK_OF_INSANITY = Isaac.GetItemIdByName("King in Yellow") -- nightmares in general need retouch
SomethingWicked.ITEMS.BOOK_OF_LEVIATHAN = Isaac.GetItemIdByName("  Book of Leviathan  ") --unfinished
SomethingWicked.ITEMS.BOOK_OF_LUCIFER = Isaac.GetItemIdByName("Book of Lucifer") -- needs retouch
SomethingWicked.ITEMS.BRAVERY = Isaac.GetItemIdByName("Bravery")
SomethingWicked.ITEMS.NAGA_VIPER = Isaac.GetItemIdByName("Naga Viper")
SomethingWicked.ITEMS.CAROLINA_REAPER = Isaac.GetItemIdByName("Carolina Reaper")
SomethingWicked.ITEMS.CAT_FOOD = Isaac.GetItemIdByName("Cat Food") -- retouch
SomethingWicked.ITEMS.FUZZY_FLY = Isaac.GetItemIdByName("Fuzzy Fly") --unfinished
SomethingWicked.ITEMS.CHAOS_HEART = Isaac.GetItemIdByName("Chaos Heart") -- entire redesign now
SomethingWicked.ITEMS.CHASM = Isaac.GetItemIdByName("Chasm") --retouch
SomethingWicked.ITEMS.CHRISMATORY = Isaac.GetItemIdByName("Chrismatory") --fix weird bug with angellic lyre. maybe move effect to different item then make this like spectre
SomethingWicked.ITEMS.CROSSED_HEART = Isaac.GetItemIdByName("Crossed Heart")
SomethingWicked.ITEMS.CURSED_CANDLE = Isaac.GetItemIdByName("Cursed Candle")
SomethingWicked.ITEMS.CURSED_CREDIT_CARD = Isaac.GetItemIdByName("Cursed Credit Card")
SomethingWicked.ITEMS.CURSED_MUSHROOM = Isaac.GetItemIdByName("Cursed Mushroom")
SomethingWicked.ITEMS.CURSE_MASK = Isaac.GetItemIdByName("Curse Mask") --unfinished
SomethingWicked.ITEMS.CUTIE_FLY_ITEM = Isaac.GetItemIdByName("Cutie Fly") --unfinished
SomethingWicked.ITEMS.DADS_WALLET = Isaac.GetItemIdByName("Lost Wallet")
SomethingWicked.ITEMS.EVIL_PIGGYBANK = Isaac.GetItemIdByName("Mammon's Piggybank") --unfinished
SomethingWicked.ITEMS.DARKNESS = Isaac.GetItemIdByName("Darkness") --unfinished
SomethingWicked.ITEMS.DEVILSKNIFE_ITEM = Isaac.GetItemIdByName("Devilsknife")
SomethingWicked.ITEMS.DEVILSTAIL = Isaac.GetItemIdByName("Devil's Tail") --REDO
SomethingWicked.ITEMS.DISCIPLES_EYE = Isaac.GetItemIdByName("Disciple's Eye") --re-do or scrap. atleast resprite
SomethingWicked.ITEMS.DUDAEL = Isaac.GetItemIdByName("Dudael") -- unfinished
SomethingWicked.ITEMS.EDENS_HEAD = Isaac.GetItemIdByName("Eden's Head")
SomethingWicked.ITEMS.ENCYCLOPEDIA = Isaac.GetItemIdByName("Encyclopedia")
SomethingWicked.ITEMS.EYE_OF_PROVIDENCE = Isaac.GetItemIdByName("Eye of Providence") -- unfinished, might also deserve a redo
SomethingWicked.ITEMS.FLYING_GUILLOTINE = Isaac.GetItemIdByName("Facestabber") -- technically finished, but i want to retouch before pushing
SomethingWicked.ITEMS.LIGHTHOUSE = Isaac.GetItemIdByName("Lighthouse") --unfinished
SomethingWicked.ITEMS.FEAR_STALKS_THE_LAND = Isaac.GetItemIdByName("Fear Stalks The Land!") --mega unfinished. dread deserves an entire retouch before i add it in
SomethingWicked.ITEMS.FETUS_IN_FETU = Isaac.GetItemIdByName("Fetus in Fetu") -- in process of retouch
SomethingWicked.ITEMS.FITUS_FORTUNUS = Isaac.GetItemIdByName("Fitus Fortunus") -- in need of retouch
SomethingWicked.ITEMS.TRINKET_SMASHER = Isaac.GetItemIdByName("Trinket Smasher")
SomethingWicked.ITEMS.GANYMEDE = Isaac.GetItemIdByName(" Ganymede ") 
SomethingWicked.ITEMS.GLITCHCITY = Isaac.GetItemIdByName("GLITCHCITY") -- possibly retouch
SomethingWicked.ITEMS.GOLDEN_CARD = Isaac.GetItemIdByName("Golden Card") -- maybe retouch or resprite
SomethingWicked.ITEMS.BOOSTER_BOX = Isaac.GetItemIdByName("Booster Box") -- give this a costume 
SomethingWicked.ITEMS.GOLDEN_WATCH = Isaac.GetItemIdByName("Golden Watch") -- unfinished, literally just needs pooling and on purchase break
SomethingWicked.ITEMS.HELLFIRE = Isaac.GetItemIdByName("Hellfire")
SomethingWicked.ITEMS.CROWN_OF_BLOOD = Isaac.GetItemIdByName("Martyral Baptism") -- unfinished, might deserve thematic redesign.
SomethingWicked.ITEMS.ICE_WAND = Isaac.GetItemIdByName("Ice Wand") -- unfinished
SomethingWicked.ITEMS.JOKER_BABY = Isaac.GetItemIdByName("Joker Baby") -- unfinished, god please finish this
SomethingWicked.ITEMS.JUSTICE_AND_SPLENDOR = Isaac.GetItemIdByName("Swords of Light") -- fix weird visual bug and maybe add some sfx
SomethingWicked.ITEMS.LANKY_MUSHROOM = Isaac.GetItemIdByName("Lanky Mushroom")
SomethingWicked.ITEMS.LANTERN_BATTERY = Isaac.GetItemIdByName("Lantern Battery") -- minor retouch
SomethingWicked.ITEMS.LAST_PRISM = Isaac.GetItemIdByName("Last Prism") -- unfinished, FINISH PLEAAAAAAAAASE
SomethingWicked.ITEMS.LEGION_ITEM = Isaac.GetItemIdByName("Legion") --unfinished, please finish me
SomethingWicked.ITEMS.DOUBLING_CHERRY = Isaac.GetItemIdByName("Doubling Cherry") -- unfinished, just needs item sprites and some minor anm2 stuff
SomethingWicked.ITEMS.LIGHT_SHARD = Isaac.GetItemIdByName("Light Shard") -- unfinished, retouch maybe
SomethingWicked.ITEMS.DARK_SHARD = Isaac.GetItemIdByName("Dark Shard") --same as above
SomethingWicked.ITEMS.FLY_SCREEN_ITEM = Isaac.GetItemIdByName("Fly Screen") -- unfinished
SomethingWicked.ITEMS.LOURDES_WATER = Isaac.GetItemIdByName("Lourdes Water") -- fix two bugs
SomethingWicked.ITEMS.LOVERS_MASK = Isaac.GetItemIdByName("Lover's Mask") -- retouch
SomethingWicked.ITEMS.MAGIC_CLAY = Isaac.GetItemIdByName("Magic Clay") -- unfinished, i really like this one though finish it
SomethingWicked.ITEMS.MINOS_ITEM = Isaac.GetItemIdByName("Minos") -- retouch me to hell
SomethingWicked.ITEMS.THE_MISTAKE = Isaac.GetItemIdByName("The Mistake") -- most unfinished item in the mod
SomethingWicked.ITEMS.MS_GONORRHEA = Isaac.GetItemIdByName("Ms. Gonorrhea") -- unfinished, just needs design
SomethingWicked.ITEMS.STAR_OF_THE_BOTTOMLESS_PIT = Isaac.GetItemIdByName("Star of the Bottomless Pit")
SomethingWicked.ITEMS.NIGHTSHADE = Isaac.GetItemIdByName("Nightshade") -- weird, retouch
SomethingWicked.ITEMS.OLD_DICE = Isaac.GetItemIdByName("Old Dice") -- check bug tet mentioned
SomethingWicked.ITEMS.OLD_URN = Isaac.GetItemIdByName("Old Urn") -- retouch
SomethingWicked.ITEMS.PENDULUM = Isaac.GetItemIdByName("Pendulum") -- so close to finished
SomethingWicked.ITEMS.PIECE_OF_SILVER = Isaac.GetItemIdByName("Piece of Silver") -- so close to finished
SomethingWicked.ITEMS.PLANCHETTE = Isaac.GetItemIdByName("Planchette") -- maybe retouch
SomethingWicked.ITEMS.PLASMA_GLOBE = Isaac.GetItemIdByName("Plasma Globe")
SomethingWicked.ITEMS.ASTIGMATISM = Isaac.GetItemIdByName("Astigmatism") -- unfinished. release with costume or die
SomethingWicked.ITEMS.RAMS_HEAD = Isaac.GetItemIdByName("Ram's Head") -- add costume for the love of god
SomethingWicked.ITEMS.RED_NIGHTMARE = Isaac.GetItemIdByName("Red") -- resprite and retouch
SomethingWicked.ITEMS.RED_CAP = Isaac.GetItemIdByName("Red Cap") -- retouch, probably. maybe just costume
SomethingWicked.ITEMS.RED_LOCKBOX = Isaac.GetItemIdByName("Red Lockbox") -- slight retouch deserved
SomethingWicked.ITEMS.RELIQUARY = Isaac.GetItemIdByName("Reliquary") -- unfinished but peak
SomethingWicked.ITEMS.REGEN_RING = Isaac.GetItemIdByName("Band of Regeneration") -- fuck i hate to say retouch and resprite on something this recent buuut
SomethingWicked.ITEMS.ROGUE_PLANET_ITEM = Isaac.GetItemIdByName("Rogue planet") -- a million retouches
SomethingWicked.ITEMS.WICKERMAN = Isaac.GetItemIdByName("Wickerman") -- give costume? also i dont like the on pickup effect
SomethingWicked.ITEMS.TEMPERANCE = Isaac.GetItemIdByName("Temperance") -- unfinished, release with costume or die
SomethingWicked.ITEMS.SAINTS_HEAD = Isaac.GetItemIdByName("Saint's Head") -- unfinished, love this one though
SomethingWicked.ITEMS.SCREW_ATTACK = Isaac.GetItemIdByName("Screw Attack") -- finish for the love of god
SomethingWicked.ITEMS.SHOTGRUB = Isaac.GetItemIdByName("The Black Death") -- possibly re-do entirely
SomethingWicked.ITEMS.SOLOMON_ITEM = Isaac.GetItemIdByName("Solomon") -- retouch
SomethingWicked.ITEMS.SPIDER_EGG = Isaac.GetItemIdByName("Spider Egg") -- retouch for the love
SomethingWicked.ITEMS.STICKER_BOOK = Isaac.GetItemIdByName("Sticker Sheet") -- unfinished
SomethingWicked.ITEMS.SUPERIORITY = Isaac.GetItemIdByName("Superiority") --idk man a costume would be nice
SomethingWicked.ITEMS.TECH_MODULO = Isaac.GetItemIdByName("Tech-Modulo") -- give me tear colour and costume
SomethingWicked.ITEMS.TERATOMA_CHUNK = Isaac.GetItemIdByName("Teratoma Chunk") -- entire redesign now
SomethingWicked.ITEMS.TIAMATS_DICE = Isaac.GetItemIdByName("Tiamat's Dice") -- minor retouch needed
SomethingWicked.ITEMS.TOMBSTONE = Isaac.GetItemIdByName("Tombstone") -- unfinished
SomethingWicked.ITEMS.TOYBOX = Isaac.GetItemIdByName("Toybox") -- retouch possibly
SomethingWicked.ITEMS.VOID_BOMBS = Isaac.GetItemIdByName("Void Bombs") -- resprite, give scatter costumes
SomethingWicked.ITEMS.VOID_EGG = Isaac.GetItemIdByName("Void Egg") --idfk man, retouch?
SomethingWicked.ITEMS.CALL_OF_THE_VOID = Isaac.GetItemIdByName("Void's Call") -- finish asap
SomethingWicked.ITEMS.STRANGE_APPLE = Isaac.GetItemIdByName("Strange Apple") -- rework visuals and movement/tile size thing
--SomethingWicked.ITEMS.WHITE_ROBE = Isaac.GetItemIdByName("White Robe") -- maybe rework entirely
SomethingWicked.ITEMS.WRATH = Isaac.GetItemIdByName("Wrath") -- minor retouch, maybe
SomethingWicked.ITEMS.YELLOW_SIGIL = Isaac.GetItemIdByName("Yellow Sigil") -- retouch when nightmares retouched
SomethingWicked.ITEMS.THE_YOYO = Isaac.GetItemIdByName("The Yo-Yo!") -- unfinished
SomethingWicked.ITEMS.HYDRUS = Isaac.GetItemIdByName("Snake")
SomethingWicked.ITEMS.WICKED_RING = Isaac.GetItemIdByName("Wicked Ring")
SomethingWicked.ITEMS.STAR_TREAT = Isaac.GetItemIdByName("Star Treat")
SomethingWicked.ITEMS.SEED_OF_EDEN = Isaac.GetItemIdByName("Earth of Adam")
SomethingWicked.ITEMS.SEED_OF_EDEN_PASSIVE = Isaac.GetItemIdByName(" Earth of Adam ")
SomethingWicked.ITEMS.DIS = Isaac.GetItemIdByName("Dis")
SomethingWicked.ITEMS.ACHERON = Isaac.GetItemIdByName("Acheron")
SomethingWicked.ITEMS.BOLTS_OF_LIGHT = Isaac.GetItemIdByName("Bolts of Light")
SomethingWicked.ITEMS.ACTIVATED_CHARCOAL = Isaac.GetItemIdByName("Activated Charcoal")
SomethingWicked.ITEMS.LIVING_WATER = Isaac.GetItemIdByName("Living Water")
SomethingWicked.ITEMS.THE_SHRINKS = Isaac.GetItemIdByName("The Shrinks")
SomethingWicked.ITEMS.ADDER_STONE = Isaac.GetItemIdByName("Adder Stone")
SomethingWicked.ITEMS.STAR_OF_PROVIDENCE = Isaac.GetItemIdByName("Mazzaroth")
SomethingWicked.ITEMS.MAGIC_EYE = Isaac.GetItemIdByName("Magic Eye")
SomethingWicked.ITEMS.SUDARIUM = Isaac.GetItemIdByName("Sudarium of Oviedo")
SomethingWicked.ITEMS.TEFILIN = Isaac.GetItemIdByName("Tefillin")
SomethingWicked.ITEMS.TWO_DOLLAR_COIN = Isaac.GetItemIdByName("Two Dollar Coin")
SomethingWicked.ITEMS.DOUBLES = Isaac.GetItemIdByName("Doubles!")
SomethingWicked.ITEMS.FULL_HOUSE = Isaac.GetItemIdByName("Full House")
SomethingWicked.ITEMS.WNIC = Isaac.GetItemIdByName("W.N.I.C.")
SomethingWicked.ITEMS.MALEDICTION = Isaac.GetItemIdByName("Mom's Wax")
SomethingWicked.ITEMS.MONOKUMA = Isaac.GetItemIdByName("Toy Bear")
SomethingWicked.ITEMS.MY_DOOM = Isaac.GetItemIdByName("MyDoom")

SomethingWicked.ITEMS.MAGIC_CLAY1 = Isaac.GetItemIdByName(" Magic Clay ")
SomethingWicked.ITEMS.MAGIC_CLAY2 = Isaac.GetItemIdByName("  Magic Clay  ")
SomethingWicked.ITEMS.MAGIC_CLAY3 = Isaac.GetItemIdByName("   Magic Clay   ")
SomethingWicked.ITEMS.FIRST_ITEM = SomethingWicked.ITEMS.AVENGER_EMBLEM
SomethingWicked.ITEMS.LAST_ITEM = SomethingWicked.ITEMS.MAGIC_CLAY3

--trinkets
SomethingWicked.TRINKETS = {}
SomethingWicked.TRINKETS.TICKET_ROLL = Isaac.GetTrinketIdByName("Ticket Roll") -- retouch
SomethingWicked.TRINKETS.BUSTED_BATTERY = Isaac.GetTrinketIdByName("Busted Battery") --unfinished
SomethingWicked.TRINKETS.GODLY_TOMATO = Isaac.GetTrinketIdByName("Godly Tomato") -- retouch
SomethingWicked.TRINKETS.HALLOWEEN_CANDY = Isaac.GetTrinketIdByName("Halloween Candy") --unfinsihed
SomethingWicked.TRINKETS.POPPET = Isaac.GetTrinketIdByName("Poppet")
SomethingWicked.TRINKETS.BOBS_HEART = Isaac.GetTrinketIdByName("Bob's Heart") -- retouch
SomethingWicked.TRINKETS.SCORCHED_PAGE = Isaac.GetTrinketIdByName("Scorched Page") --unfinished
SomethingWicked.TRINKETS.CATS_EYE = Isaac.GetTrinketIdByName("Cat's Eye")
SomethingWicked.TRINKETS.MEAL_COUPON = Isaac.GetTrinketIdByName("Meal Coupon") -- unfinished
SomethingWicked.TRINKETS.DAMNED_SOUL = Isaac.GetTrinketIdByName("Damned Soul")
SomethingWicked.TRINKETS.VIRTUOUS_SOUL = Isaac.GetTrinketIdByName("Virtuous Soul") --remove or redesign
SomethingWicked.TRINKETS.DEMON_CORE = Isaac.GetTrinketIdByName("Demon Core") -- retouch
SomethingWicked.TRINKETS.DEMONIUM_PAGE = Isaac.GetTrinketIdByName("Demonium Page")
SomethingWicked.TRINKETS.DICE_ROLLER = Isaac.GetTrinketIdByName("Dice Roller")
SomethingWicked.TRINKETS.EMPTY_BOOK = Isaac.GetTrinketIdByName("Blank Book") -- might deserve a resprite
SomethingWicked.TRINKETS.GACHAPON = Isaac.GetTrinketIdByName("Gachapon") -- needs retouch, maybe resprite?
SomethingWicked.TRINKETS.GIFT_CARD = Isaac.GetTrinketIdByName("Gift Card") -- needs retouch
SomethingWicked.TRINKETS.CARD_GRAVEYARD = Isaac.GetTrinketIdByName("Card Graveyard") -- unfinished
SomethingWicked.TRINKETS.CELLPHONE_BATTERY = Isaac.GetTrinketIdByName("Cellphone Battery")
SomethingWicked.TRINKETS.LUCKY_BUTTON = Isaac.GetTrinketIdByName("Lucky Button") --unfinished, just needs sprite
SomethingWicked.TRINKETS.MR_SKITS = Isaac.GetTrinketIdByName("Mr. Skits") -- unfinished
SomethingWicked.TRINKETS.OWL_FEATHER = Isaac.GetTrinketIdByName("Owl Feather") -- maybe resprite? animals r hard
SomethingWicked.TRINKETS.NIGHTMARE_FUEL = Isaac.GetTrinketIdByName("Nightmare Fuel") -- retouch this to hell and back
SomethingWicked.TRINKETS.POWER_INVERTER = Isaac.GetTrinketIdByName("Power Inverter")
SomethingWicked.TRINKETS.RED_KEYCHAIN = Isaac.GetTrinketIdByName("Red Keychain") -- unfinished
SomethingWicked.TRINKETS.SURGICAL_MASK = Isaac.GetTrinketIdByName("Surgical Mask") -- unfinished, justn eeds sprite
SomethingWicked.TRINKETS.SCORCHED_WOOD = Isaac.GetTrinketIdByName("Scorched Wood") -- retouch
SomethingWicked.TRINKETS.STONE_KEY = Isaac.GetTrinketIdByName("Stone Key")
SomethingWicked.TRINKETS.SUGAR_COATED_PILL = Isaac.GetTrinketIdByName("Sugar Coated Pill") --retouch
SomethingWicked.TRINKETS.TREASURERS_KEY = Isaac.GetTrinketIdByName("Treasurer's Key")
SomethingWicked.TRINKETS.CURSED_KEY = Isaac.GetTrinketIdByName("Cursed Key")
SomethingWicked.TRINKETS.TWO_OF_COINS = Isaac.GetTrinketIdByName("Two of Coins") -- retouch. gotta do the gold thing probably.
SomethingWicked.TRINKETS.VOID_HEART = Isaac.GetTrinketIdByName("Void Heart") -- retouch rn
SomethingWicked.TRINKETS.ZZZZZZ_MAGNET = Isaac.GetTrinketIdByName("ZZZZZZ Magnet") -- unfinished
SomethingWicked.TRINKETS.PRINT_OF_INDULGENCE = Isaac.GetTrinketIdByName("Indulgence Print")
SomethingWicked.TRINKETS.SAMPLE_BOX = Isaac.GetTrinketIdByName("Sample Box")
SomethingWicked.TRINKETS.FLUKE_WORM = Isaac.GetTrinketIdByName("Fluke Worm")
SomethingWicked.TRINKETS.VICODIN = Isaac.GetTrinketIdByName("Vicodin")
SomethingWicked.TRINKETS.OPTIONS_TRINKET = Isaac.GetTrinketIdByName("options trinket")

SomethingWicked.TRINKETS.FIRST_TRINKET = SomethingWicked.TRINKETS.CATS_EYE
SomethingWicked.TRINKETS.LAST_TRINKET = SomethingWicked.TRINKETS.OPTIONS_TRINKET

--CARDS
SomethingWicked.CARDS = {}
mod.CARDS.MAGPIE_EYE = Isaac.GetCardIdByName("MagpieEye")
mod.CARDS.MAGPIE_EYE_BOON = Isaac.GetCardIdByName("MagpieEyeBoon")
mod.CARDS.KNIGHT_OF_DIAMONDS = Isaac.GetCardIdByName("KnightOfDiamonds")
mod.CARDS.KNIGHT_OF_HEARTS = Isaac.GetCardIdByName("KnightOfHearts")
mod.CARDS.KNIGHT_OF_SPADES = Isaac.GetCardIdByName("KnightOfSpades")
mod.CARDS.KNIGHT_OF_CLUBS = Isaac.GetCardIdByName("KnightOfClubs")
mod.CARDS.THE_GAME = Isaac.GetCardIdByName("TheGame") --that you just lost
mod.CARDS.STONE_OF_THE_PIT = Isaac.GetCardIdByName("StoneOfThePit")

mod.CARDS.THOTH_THE_ADJUSTMENT = Isaac.GetCardIdByName("TheAdjustment")
mod.CARDS.THOTH_THE_AEON = Isaac.GetCardIdByName("TheAeon")
mod.CARDS.THOTH_ART = Isaac.GetCardIdByName("TheArt")
mod.CARDS.THOTH_FORTUNE = Isaac.GetCardIdByName("Fortune")
mod.CARDS.THOTH_LUST = Isaac.GetCardIdByName("Lust")
mod.CARDS.THOTH_THE_MAGUS = Isaac.GetCardIdByName("TheMagus")

mod.NULL = {}
mod.NULL.LUSTEFFECT = Isaac.GetNullItemIdByName("lust null item")
mod.NULL.VIATHAN = Isaac.GetNullItemIdByName("nullviathan")

local itemPoolEnum = mod.ItemPools
mod.CONST.POOLS = {
    [itemPoolEnum.TERATOMA_BEGGAR] = {
        { item = SomethingWicked.ITEMS.FETUS_IN_FETU, weight = 1},
        { item = SomethingWicked.ITEMS.TERATOMA_CHUNK, weight = 1}
    }
}

mod.CONST.DUMMYITEMS = {
    BLANKBOOK_BOOKWORM = Isaac.GetItemIdByName("[sw] bookworm dummy item"),
    BLANKBOOK_GOLDEN = Isaac.GetItemIdByName("[sw] golden bookworm dummy item")
}