local mod = SomethingWicked

CollectibleType.SOMETHINGWICKED_3D_GLASSES = Isaac.GetItemIdByName(" 3D Glasses ")
CollectibleType.SOMETHINGWICKED_ABANDONED_BOX = Isaac.GetItemIdByName("Abandoned Box")
CollectibleType.SOMETHINGWICKED_BRITTLE_DAGGER = Isaac.GetItemIdByName("Brittle Dagger") --unfinished
CollectibleType.SOMETHINGWICKED_DAGGER_HANDLE = Isaac.GetItemIdByName("Dagger Handle") --unfinished
CollectibleType.SOMETHINGWICKED_AIR_FRESHENER = Isaac.GetItemIdByName("Air Freshener") --unfinished
CollectibleType.SOMETHINGWICKED_APOLLYONS_CROWN = Isaac.GetItemIdByName("Apollyon's Crown") --retouch
CollectibleType.SOMETHINGWICKED_ASSIST_TROPHY = Isaac.GetItemIdByName("Assist Trophy")
CollectibleType.SOMETHINGWICKED_AVENGER_EMBLEM = Isaac.GetItemIdByName("Avenger Emblem")
CollectibleType.SOMETHINGWICKED_BABY_MANDRAKE = Isaac.GetItemIdByName("Baby Mandrake") --unfinished
CollectibleType.SOMETHINGWICKED_BALROGS_HEAD = Isaac.GetItemIdByName("Balrog's Head")
CollectibleType.SOMETHINGWICKED_BALROGS_HEART = Isaac.GetItemIdByName("Balrog's Heart") --unfinished (might deserve not balrog-ness)
CollectibleType.SOMETHINGWICKED_BANANA_MILK = Isaac.GetItemIdByName("Banana Milk") --unfinished
CollectibleType.SOMETHINGWICKED_ELECTRIC_DICE = Isaac.GetItemIdByName("Electric Dice")
CollectibleType.SOMETHINGWICKED_BIRETTA = Isaac.GetItemIdByName("Biretta") -- touch up
CollectibleType.SOMETHINGWICKED_BLACK_SALT = Isaac.GetItemIdByName("Black Salt") --unfinsihed
CollectibleType.SOMETHINGWICKED_BLOOD_HAIL = Isaac.GetItemIdByName("Blood Hail") --unfinished
CollectibleType.SOMETHINGWICKED_BOLINE = Isaac.GetItemIdByName("Boline")
CollectibleType.SOMETHINGWICKED_BOOK_OF_INSANITY = Isaac.GetItemIdByName("Book of Insanity") -- nightmares in general need retouch
CollectibleType.SOMETHINGWICKED_BOOK_OF_LEVIATHAN = Isaac.GetItemIdByName("  Book of Leviathan  ") --unfinished
CollectibleType.SOMETHINGWICKED_BOOK_OF_LUCIFER = Isaac.GetItemIdByName("Book of Lucifer") -- needs retouch
CollectibleType.SOMETHINGWICKED_BOTTLE_OF_SHAMPOO = Isaac.GetItemIdByName("Bottle of Shampoo") -- unfinished
CollectibleType.SOMETHINGWICKED_SPECIAL_HERBS_BOX = Isaac.GetItemIdByName("Special Herbs Boxset") --unfinished
CollectibleType.SOMETHINGWICKED_BRAVERY = Isaac.GetItemIdByName("Bravery")
CollectibleType.SOMETHINGWICKED_BROKEN_BELL = Isaac.GetItemIdByName("Broken Bell") --unfinished
CollectibleType.SOMETHINGWICKED_NAGA_VIPER = Isaac.GetItemIdByName("Naga Viper")
CollectibleType.SOMETHINGWICKED_CAROLINA_REAPER = Isaac.GetItemIdByName("Carolina Reaper")
CollectibleType.SOMETHINGWICKED_CAT_FOOD = Isaac.GetItemIdByName("Cat Food") -- retouch
CollectibleType.SOMETHINGWICKED_CAT_TEASER = Isaac.GetItemIdByName("Cat Teaser")
CollectibleType.SOMETHINGWICKED_FUZZY_FLY = Isaac.GetItemIdByName("Fuzzy Fly") --unfinished
CollectibleType.SOMETHINGWICKED_CHAOS_HEART = Isaac.GetItemIdByName("Chaos Heart") -- entire redesign now
CollectibleType.SOMETHINGWICKED_CHASM = Isaac.GetItemIdByName("Chasm") --retouch
CollectibleType.SOMETHINGWICKED_BOOK_OF_EXODUS = Isaac.GetItemIdByName("Book of Exodus")
CollectibleType.SOMETHINGWICKED_WOODEN_DICE = Isaac.GetItemIdByName("Wooden Dice")
CollectibleType.SOMETHINGWICKED_CHRISMATORY = Isaac.GetItemIdByName("Chrismatory") --fix weird bug with angellic lyre. maybe move effect to different item then make this like spectre
CollectibleType.SOMETHINGWICKED_WICKED_SOUL = Isaac.GetItemIdByName("Wicked Soul")
CollectibleType.SOMETHINGWICKED_CROSSED_HEART = Isaac.GetItemIdByName("Crossed Heart")
CollectibleType.SOMETHINGWICKED_CURSED_CANDLE = Isaac.GetItemIdByName("Cursed Candle")
CollectibleType.SOMETHINGWICKED_CURSED_CREDIT_CARD = Isaac.GetItemIdByName("Cursed Credit Card")
CollectibleType.SOMETHINGWICKED_CURSED_MUSHROOM = Isaac.GetItemIdByName("Cursed Mushroom")
CollectibleType.SOMETHINGWICKED_CURSE_MASK = Isaac.GetItemIdByName("Curse Mask") --unfinished
CollectibleType.SOMETHINGWICKED_BLACK_MOON_MEDALLION = Isaac.GetItemIdByName("Black Moon Medallion") --unfinished
CollectibleType.SOMETHINGWICKED_CUTIE_FLY_ITEM = Isaac.GetItemIdByName("Cutie Fly") --unfinished
CollectibleType.SOMETHINGWICKED_DADS_WALLET = Isaac.GetItemIdByName("Lost Wallet")
CollectibleType.SOMETHINGWICKED_EVIL_PIGGYBANK = Isaac.GetItemIdByName("Mammon's Piggybank") --unfinished
CollectibleType.SOMETHINGWICKED_DARKNESS = Isaac.GetItemIdByName("Darkness") --unfinished
CollectibleType.SOMETHINGWICKED_DEVILSKNIFE_ITEM = Isaac.GetItemIdByName("Devilsknife")
CollectibleType.SOMETHINGWICKED_DEVILSTAIL = Isaac.GetItemIdByName("Devil's Tail") --REDO
CollectibleType.SOMETHINGWICKED_DISCIPLES_EYE = Isaac.GetItemIdByName("Disciple's Eye") --re-do or scrap. atleast resprite
CollectibleType.SOMETHINGWICKED_MTRBITEM = Isaac.GetItemIdByName("Curse of Ares") -- scrap, probably
CollectibleType.SOMETHINGWICKED_D_STOCK = Isaac.GetItemIdByName("D-Stock") -- make work with devil deals again
CollectibleType.SOMETHINGWICKED_DUDAEL = Isaac.GetItemIdByName("Dudael") -- unfinished
CollectibleType.SOMETHINGWICKED_EDENS_HEAD = Isaac.GetItemIdByName("Eden's Head")
CollectibleType.SOMETHINGWICKED_ENCYCLOPEDIA = Isaac.GetItemIdByName("Encyclopedia")
CollectibleType.SOMETHINGWICKED_EYE_OF_PROVIDENCE = Isaac.GetItemIdByName("Eye of Providence") -- unfinished, might also deserve a redo
CollectibleType.SOMETHINGWICKED_FLYING_GUILLOTINE = Isaac.GetItemIdByName("Facestabber") -- technically finished, but i want to retouch before pushing
CollectibleType.SOMETHINGWICKED_LIGHTHOUSE = Isaac.GetItemIdByName("Lighthouse") --unfinished
CollectibleType.SOMETHINGWICKED_FEAR_STALKS_THE_LAND = Isaac.GetItemIdByName("Fear Stalks The Land!") --mega unfinished. dread deserves an entire retouch before i add it in
CollectibleType.SOMETHINGWICKED_FETUS_IN_FETU = Isaac.GetItemIdByName("Fetus in Fetu") -- in process of retouch
CollectibleType.SOMETHINGWICKED_FIBROUS_DYSPLASIA = Isaac.GetItemIdByName("Fibrous Dysplasia") --scrapped, could probably make something else with the general idea
CollectibleType.SOMETHINGWICKED_FITUS_FORTUNUS = Isaac.GetItemIdByName("Fitus Fortunus") -- in need of retouch
CollectibleType.SOMETHINGWICKED_TRINKET_SMASHER = Isaac.GetItemIdByName("Trinket Smasher")
CollectibleType.SOMETHINGWICKED_GANYMEDE = Isaac.GetItemIdByName(" Ganymede ") --unfinished, make this cool
CollectibleType.SOMETHINGWICKED_GOLDEN_CARD = Isaac.GetItemIdByName("Golden Card") -- maybe retouch or resprite
CollectibleType.SOMETHINGWICKED_BOOSTER_BOX = Isaac.GetItemIdByName("Booster Box") -- give this a costume 
CollectibleType.SOMETHINGWICKED_GOLDEN_WATCH = Isaac.GetItemIdByName("Golden Watch") -- unfinished, literally just needs pooling and on purchase break
CollectibleType.SOMETHINGWICKED_HELLFIRE = Isaac.GetItemIdByName("Hellfire")
CollectibleType.SOMETHINGWICKED_CROWN_OF_BLOOD = Isaac.GetItemIdByName("Martyral Baptism") -- unfinished, might deserve thematic redesign.
CollectibleType.SOMETHINGWICKED_ICE_WAND = Isaac.GetItemIdByName("Ice Wand") -- unfinished
CollectibleType.SOMETHINGWICKED_JOKER_BABY = Isaac.GetItemIdByName("Joker Baby") -- unfinished, god please finish this
CollectibleType.SOMETHINGWICKED_JUSTICE_AND_SPLENDOR = Isaac.GetItemIdByName("Swords of Light") -- fix weird visual bug and maybe add some sfx
CollectibleType.SOMETHINGWICKED_KNAVE_OF_HEARTS = Isaac.GetItemIdByName("Knave of Hearts") -- scrapped
CollectibleType.SOMETHINGWICKED_LANKY_MUSHROOM = Isaac.GetItemIdByName("Lanky Mushroom")
CollectibleType.SOMETHINGWICKED_LANTERN_BATTERY = Isaac.GetItemIdByName("Lantern Battery") -- minor retouch
CollectibleType.SOMETHINGWICKED_LAST_PRISM = Isaac.GetItemIdByName("Last Prism") -- unfinished, FINISH PLEAAAAAAAAASE
CollectibleType.SOMETHINGWICKED_LEGION_ITEM = Isaac.GetItemIdByName("Legion") --unfinished, please finish me
CollectibleType.SOMETHINGWICKED_DOUBLING_CHERRY = Isaac.GetItemIdByName("Doubling Cherry") -- unfinished, just needs item sprites and some minor anm2 stuff
CollectibleType.SOMETHINGWICKED_LIGHT_SHARD = Isaac.GetItemIdByName("Light Shard") -- unfinished, retouch maybe
CollectibleType.SOMETHINGWICKED_DARK_SHARD = Isaac.GetItemIdByName("Dark Shard") --same as above
CollectibleType.SOMETHINGWICKED_LITTLE_ATTRACTOR_ITEM = Isaac.GetItemIdByName("Little Attractor") -- unfinished
CollectibleType.SOMETHINGWICKED_LOURDES_WATER = Isaac.GetItemIdByName("Lourdes Water") -- fix two bugs
CollectibleType.SOMETHINGWICKED_LOVERS_MASK = Isaac.GetItemIdByName("Lover's Mask") -- retouch
CollectibleType.SOMETHINGWICKED_MAGIC_CLAY = Isaac.GetItemIdByName("Magic Clay") -- unfinished, i really like this one though finish it
CollectibleType.SOMETHINGWICKED_MAMMONS_TOOTH = Isaac.GetItemIdByName("Mammon's Tooth") -- scrapped
CollectibleType.SOMETHINGWICKED_MARBLE_SPROUT = Isaac.GetItemIdByName("Marble Sprout") -- unfinished
CollectibleType.SOMETHINGWICKED_TASK_MANAGER = Isaac.GetItemIdByName("Task Manager") -- unfinished
CollectibleType.SOMETHINGWICKED_MINOS_ITEM = Isaac.GetItemIdByName("Minos") -- retouch me to hell
CollectibleType.SOMETHINGWICKED_CRYING_MINOTAUR = Isaac.GetItemIdByName("Crying Minotaur") -- unfinished, see FSTL (might deserve not-radiohead ness)
CollectibleType.SOMETHINGWICKED_THE_MISTAKE = Isaac.GetItemIdByName("The Mistake") -- most unfinished item in the mod
CollectibleType.SOMETHINGWICKED_MOSAIC_SHARD = Isaac.GetItemIdByName("Prismatic Shard") -- dont remember if this was scrapped or unfinished
CollectibleType.SOMETHINGWICKED_MS_GONORRHEA = Isaac.GetItemIdByName("Ms. Gonorrhea") -- unfinished, just needs design
CollectibleType.SOMETHINGWICKED_STAR_OF_THE_BOTTOMLESS_PIT = Isaac.GetItemIdByName("Star of the Bottomless Pit")
CollectibleType.SOMETHINGWICKED_PLAGUE_OF_WORMWOOD = Isaac.GetItemIdByName("Plague of Wormwood") -- unfinished, retouch
CollectibleType.SOMETHINGWICKED_DEBUGGER = Isaac.GetItemIdByName("Debugger") -- unfinished, hoo boy
CollectibleType.SOMETHINGWICKED_NIGHTSHADE = Isaac.GetItemIdByName("Nightshade") -- weird, retouch
CollectibleType.SOMETHINGWICKED_OLD_BELL = Isaac.GetItemIdByName("Hushed Bell") -- resprite/thematic redesign, add shader and sfx, then boom its done
CollectibleType.SOMETHINGWICKED_OLD_DICE = Isaac.GetItemIdByName("Old Dice") -- check bug tet mentioned
CollectibleType.SOMETHINGWICKED_OLD_URN = Isaac.GetItemIdByName("Old Urn") -- retouch
CollectibleType.SOMETHINGWICKED_OSTEOPHAGY = Isaac.GetItemIdByName("Osteophagy") -- ew, scrapped
CollectibleType.SOMETHINGWICKED_PENDULUM = Isaac.GetItemIdByName("Pendulum") -- so close to finished
CollectibleType.SOMETHINGWICKED_PHOBOS_AND_DEIMOS = Isaac.GetItemIdByName("Phobos and Deimos") -- unfinished but weeird
CollectibleType.SOMETHINGWICKED_PIECE_OF_SILVER = Isaac.GetItemIdByName("Piece of Silver") -- so close to finished
CollectibleType.SOMETHINGWICKED_PLANCHETTE = Isaac.GetItemIdByName("Planchette") -- maybe retouch
CollectibleType.SOMETHINGWICKED_PLASMA_GLOBE = Isaac.GetItemIdByName("Plasma Globe")
CollectibleType.SOMETHINGWICKED_POSSUMS_EAR = Isaac.GetItemIdByName("Possum's Ear") -- scrap me
CollectibleType.SOMETHINGWICKED_POSSUMS_HEAD = Isaac.GetItemIdByName("Possum's Head") -- scrap me
CollectibleType.SOMETHINGWICKED_PRESSURE_VALVE = Isaac.GetItemIdByName("Pressure Valve") -- unfinished. release with costume or die
CollectibleType.SOMETHINGWICKED_PRISMATIC_MUSHROOM = Isaac.GetItemIdByName("Prismatic Mushroom") -- unfinished
CollectibleType.SOMETHINGWICKED_RAMS_HEAD = Isaac.GetItemIdByName("Ram's Head") -- add costume for the love of god
CollectibleType.SOMETHINGWICKED_RED_NIGHTMARE = Isaac.GetItemIdByName("Red") -- resprite and retouch
CollectibleType.SOMETHINGWICKED_RED_CAP = Isaac.GetItemIdByName("Red Cap") -- retouch, probably. maybe just costume
CollectibleType.SOMETHINGWICKED_RED_LOCKBOX = Isaac.GetItemIdByName("Red Lockbox") -- slight retouch deserved
CollectibleType.SOMETHINGWICKED_RED_QUEEN = Isaac.GetItemIdByName("Red Queen") -- gretouch and unfinished
CollectibleType.SOMETHINGWICKED_RELIQUARY = Isaac.GetItemIdByName("Reliquary") -- unfinished but peak
CollectibleType.SOMETHINGWICKED_REGEN_RING = Isaac.GetItemIdByName("Band of Regeneration") -- fuck i hate to say retouch and resprite on something this recent buuut
CollectibleType.SOMETHINGWICKED_ROGUE_PLANET_ITEM = Isaac.GetItemIdByName("Rogue planet") -- a million retouches
CollectibleType.SOMETHINGWICKED_SACRIFICIAL_EFFIGY = Isaac.GetItemIdByName("Sacrificial Effigy") -- maybe resprite? and give costume? also i dont like the on pickup effect
CollectibleType.SOMETHINGWICKED_TEMPERANCE = Isaac.GetItemIdByName("Temperance") -- unfinished, release with costume or die
CollectibleType.SOMETHINGWICKED_SAINTS_HEAD = Isaac.GetItemIdByName("Saint's Head") -- unfinished, love this one though
CollectibleType.SOMETHINGWICKED_SAMYAZAS_PLUME = Isaac.GetItemIdByName("Samyaza's Plume") -- unfinished, maybe scrapped
CollectibleType.SOMETHINGWICKED_SCREW_ATTACK = Isaac.GetItemIdByName("Screw Attack") -- finish for the love of god
CollectibleType.SOMETHINGWICKED_SHOTGRUB = Isaac.GetItemIdByName("The Black Death") -- possibly re-do entirely
CollectibleType.SOMETHINGWICKED_SILVER_RING = Isaac.GetItemIdByName("Silver Ring")
CollectibleType.SOMETHINGWICKED_SOLOMON_ITEM = Isaac.GetItemIdByName("Solomon") -- retouch
CollectibleType.SOMETHINGWICKED_SPIDER_EGG = Isaac.GetItemIdByName("Spider Egg") -- retouch for the love
CollectibleType.SOMETHINGWICKED_SPOOL_OF_YARN = Isaac.GetItemIdByName("Spool of Yarn") -- unfinished
CollectibleType.SOMETHINGWICKED_STAR_SPAWN = Isaac.GetItemIdByName("Star Spawn")
CollectibleType.SOMETHINGWICKED_STICKER_BOOK = Isaac.GetItemIdByName("Sticker Book") -- unfinished
CollectibleType.SOMETHINGWICKED_SUPERIORITY = Isaac.GetItemIdByName("Superiority") --idk man a costume would be nice
CollectibleType.SOMETHINGWICKED_TECH_MODULO = Isaac.GetItemIdByName("Tech-Modulo") -- give me tear colour and costume
CollectibleType.SOMETHINGWICKED_TERATOMA_CHUNK = Isaac.GetItemIdByName("Teratoma Chunk") -- entire redesign now
CollectibleType.SOMETHINGWICKED_TIAMATS_DICE = Isaac.GetItemIdByName("Tiamat's Dice") -- minor retouch needed
CollectibleType.SOMETHINGWICKED_TOMBSTONE = Isaac.GetItemIdByName("Tombstone") -- unfinished
CollectibleType.SOMETHINGWICKED_TOYBOX = Isaac.GetItemIdByName("Toybox") -- retouch possibly
CollectibleType.SOMETHINGWICKED_VOID_BOMBS = Isaac.GetItemIdByName("Void Bombs") -- resprite, give scatter costumes
CollectibleType.SOMETHINGWICKED_VOID_EGG = Isaac.GetItemIdByName("Void Egg") --idfk man, retouch?
CollectibleType.SOMETHINGWICKED_CALL_OF_THE_VOID = Isaac.GetItemIdByName("Void's Call") -- finish asap
CollectibleType.SOMETHINGWICKED_STRANGE_APPLE = Isaac.GetItemIdByName("Strange Apple") -- rework visuals and movement/tile size thing
CollectibleType.SOMETHINGWICKED_WHITE_ROBE = Isaac.GetItemIdByName("White Robe") -- maybe rework entirely
CollectibleType.SOMETHINGWICKED_WHITE_ROSE = Isaac.GetItemIdByName("White Rose")
CollectibleType.SOMETHINGWICKED_WOODEN_HORN = Isaac.GetItemIdByName("Wooden Horn")
CollectibleType.SOMETHINGWICKED_WRATH = Isaac.GetItemIdByName("Wrath") -- minor retouch, maybe
CollectibleType.SOMETHINGWICKED_YELLOW_SIGIL = Isaac.GetItemIdByName("Yellow Sigil") -- retouch when nightmares retouched
CollectibleType.SOMETHINGWICKED_THE_YOYO = Isaac.GetItemIdByName("The Yo-Yo!") -- unfinished
CollectibleType.SOMETHINGWICKED_HYDRUS = Isaac.GetItemIdByName("Snake")
CollectibleType.SOMETHINGWICKED_HYDRA = Isaac.GetItemIdByName("Hydra") --unfinished

TrinketType.SOMETHINGWICKED_TICKET_ROLL = Isaac.GetTrinketIdByName("Ticket Roll") -- retouch
TrinketType.SOMETHINGWICKED_BUSTED_BATTERY = Isaac.GetTrinketIdByName("Busted Battery") --unfinished
TrinketType.SOMETHINGWICKED_GODLY_TOMATO = Isaac.GetTrinketIdByName("Godly Tomato") -- retouch
TrinketType.SOMETHINGWICKED_HALLOWEEN_CANDY = Isaac.GetTrinketIdByName("Halloween Candy") --unfinsihed
TrinketType.SOMETHINGWICKED_POPPET = Isaac.GetTrinketIdByName("Poppet")
TrinketType.SOMETHINGWICKED_BOBS_HEART = Isaac.GetTrinketIdByName("Bob's Heart") -- retouch
TrinketType.SOMETHINGWICKED_SCORCHED_PAGE = Isaac.GetTrinketIdByName("Scorched Page") --unfinished
TrinketType.SOMETHINGWICKED_CATS_EYE = Isaac.GetTrinketIdByName("Cat's Eye")
TrinketType.SOMETHINGWICKED_MEAL_COUPON = Isaac.GetTrinketIdByName("Meal Coupon") -- unfinished
TrinketType.SOMETHINGWICKED_DAMNED_SOUL = Isaac.GetTrinketIdByName("Damned Soul")
TrinketType.SOMETHINGWICKED_VIRTUOUS_SOUL = Isaac.GetTrinketIdByName("Virtuous Soul") --remove or redesign
TrinketType.SOMETHINGWICKED_DEMON_CORE = Isaac.GetTrinketIdByName("Demon Core") -- retouch
TrinketType.SOMETHINGWICKED_DEMONIUM_PAGE = Isaac.GetTrinketIdByName("Demonium Page")
TrinketType.SOMETHINGWICKED_DICE_ROLLER = Isaac.GetTrinketIdByName("Dice Roller")
TrinketType.SOMETHINGWICKED_EMPTY_BOOK = Isaac.GetTrinketIdByName("Blank Book") -- might deserve a resprite
TrinketType.SOMETHINGWICKED_FLOATING_POINT_BUG = Isaac.GetTrinketIdByName("Floating Point Bug") -- unfinished
TrinketType.SOMETHINGWICKED_BAG_OF_MUGWORTS = Isaac.GetTrinketIdByName("Bag of Mugworts") -- unfinished, both these locusts are in need of retouch
TrinketType.SOMETHINGWICKED_GACHAPON = Isaac.GetTrinketIdByName("Gachapon") -- needs retouch, maybe resprite?
TrinketType.SOMETHINGWICKED_GIFT_CARD = Isaac.GetTrinketIdByName("Gift Card") -- needs retouch
TrinketType.SOMETHINGWICKED_CARD_GRAVEYARD = Isaac.GetTrinketIdByName("Card Graveyard") -- unfinished
TrinketType.SOMETHINGWICKED_CELLPHONE_BATTERY = Isaac.GetTrinketIdByName("Cellphone Battery")
TrinketType.SOMETHINGWICKED_LUCKY_BUTTON = Isaac.GetTrinketIdByName("Lucky Button") --unfinished, just needs sprite
TrinketType.SOMETHINGWICKED_MR_SKITS = Isaac.GetTrinketIdByName("Mr. Skits") -- unfinished
TrinketType.SOMETHINGWICKED_OWL_FEATHER = Isaac.GetTrinketIdByName("Owl Feather") -- maybe resprite? animals r hard
TrinketType.SOMETHINGWICKED_NIGHTMARE_FUEL = Isaac.GetTrinketIdByName("Nightmare Fuel") -- retouch this to hell and back
TrinketType.SOMETHINGWICKED_VIRTUE = Isaac.GetTrinketIdByName("Virtue") -- unfinished as hell
TrinketType.SOMETHINGWICKED_POWER_INVERTER = Isaac.GetTrinketIdByName("Power Inverter")
TrinketType.SOMETHINGWICKED_RED_KEYCHAIN = Isaac.GetTrinketIdByName("Red Keychain") -- unfinished
TrinketType.SOMETHINGWICKED_SURGICAL_MASK = Isaac.GetTrinketIdByName("Surgical Mask") -- unfinished, justn eeds sprite
TrinketType.SOMETHINGWICKED_SCORCHED_WOOD = Isaac.GetTrinketIdByName("Scorched Wood") -- retouch
TrinketType.SOMETHINGWICKED_STONE_KEY = Isaac.GetTrinketIdByName("Stone Key") -- retouch like rn
TrinketType.SOMETHINGWICKED_SUGAR_COATED_PILL = Isaac.GetTrinketIdByName("Sugar Coated Pill") --retouch
TrinketType.SOMETHINGWICKED_TREASURERS_KEY = Isaac.GetTrinketIdByName("Treasurer's Key")
TrinketType.SOMETHINGWICKED_CURSED_KEY = Isaac.GetTrinketIdByName("Cursed Key")
TrinketType.SOMETHINGWICKED_TWO_OF_COINS = Isaac.GetTrinketIdByName("Two of Coins") -- retouch. gotta do the gold thing probably.
TrinketType.SOMETHINGWICKED_VOID_HEART = Isaac.GetTrinketIdByName("Void Heart") -- retouch rn
TrinketType.SOMETHINGWICKED_ZZZZZZ_MAGNET = Isaac.GetTrinketIdByName("ZZZZZZ Magnet") -- unfinished

Card.SOMETHINGWICKED_MAGPIE_EYE = Isaac.GetCardIdByName("MagpieEye")
Card.SOMETHINGWICKED_MAGPIE_EYE_BOON = Isaac.GetCardIdByName("MagpieEyeBoon")

FamiliarVariant.SOMETHINGWICKED_FUZZY_FLY = Isaac.GetEntityVariantByName("Fuzzy Fly Familiar")
FamiliarVariant.SOMETHINGWICKED_CUTIE_FLY = Isaac.GetEntityVariantByName("Cutie Fly")
FamiliarVariant.SOMETHINGWICKED_DEVILSKNIFE = Isaac.GetEntityVariantByName("Devilsknife")
FamiliarVariant.SOMETHINGWICKED_DUDAEL_GHOST = Isaac.GetEntityVariantByName("Dudael Ghost")
FamiliarVariant.SOMETHINGWICKED_BIG_WISP = Isaac.GetEntityVariantByName("Fat Wisp")
FamiliarVariant.SOMETHINGWICKED_JUSTICE_AND_SPLENDOR = Isaac.GetEntityVariantByName("Splendorous Sword")
FamiliarVariant.SOMETHINGWICKED_PRISM_HELPER = Isaac.GetEntityVariantByName("Prism Helper")
FamiliarVariant.SOMETHINGWICKED_LEGION = Isaac.GetEntityVariantByName("Legion Familiar")
FamiliarVariant.SOMETHINGWICKED_LEGION_B = Isaac.GetEntityVariantByName("Legion Familiar B")
FamiliarVariant.SOMETHINGWICKED_ALMOST_ISAAC = Isaac.GetEntityVariantByName("Cherry Isaac Familiar")
FamiliarVariant.SOMETHINGWICKED_LITTLE_ATTRACTOR = Isaac.GetEntityVariantByName("Little Attractor Familiar")
FamiliarVariant.SOMETHINGWICKED_MINOS_HEAD = Isaac.GetEntityVariantByName("Minos (Head)")
FamiliarVariant.SOMETHINGWICKED_MINOS_BODY = Isaac.GetEntityVariantByName("Minos (Body)")
FamiliarVariant.SOMETHINGWICKED_THE_MISTAKE = Isaac.GetEntityVariantByName("Mistake Familiar") -- giga unfinished
FamiliarVariant.SOMETHINGWICKED_MS_GONORRHEA = Isaac.GetEntityVariantByName("Ms. Gonorrhea")


local itemPoolEnum = mod.ENUMS.ItemPools
mod.CONST.POOLS = {
    [itemPoolEnum.TERATOMA_BEGGAR] = {
        { item = CollectibleType.SOMETHINGWICKED_FETUS_IN_FETU, weight = 1},
        { item = CollectibleType.SOMETHINGWICKED_TERATOMA_CHUNK, weight = 1}
    }
}

mod.CONST.DUMMYITEMS = {
    APOLLYONS_CROWN = Isaac.GetItemIdByName("[sw] apollyons crown dummy item"),
    LUST_NULLITEM = Isaac.GetItemIdByName("[sw] lust dummy helper"),
    BLANKBOOK_BOOKWORM = Isaac.GetItemIdByName("[sw] bookworm dummy item")
}